### ISSUE TITLE
pip ratarmount and "!ratarmount" in the Jupiter notebook...

### ISSUE THREAD

**Issue by tinaok** [NCAR/xtar#3]
Hi @andersy005 , @kmpaul 
https://github.com/tinaok/xtar/blob/master/notebooks/tar-netcdf-HPCrealdata.ipynb
I was trying with NFS disk space on our HPC system.
ratarmount installed in my conda environment but can not access; may be I missunderstanding something?

As you can see, I installed libfuse in the same conda environment.

**Comment by andersy005** [comment]
Hi @tinaok, 

In the notebook, I am noticing that your default shell is `/bin/sh`


```
/bin/sh: ratarmount: command not found
CPU times: user 4 ms, sys: 4 ms, total: 8 ms
Wall time: 165 ms
```
From your regular terminal, what is the output of `echo $SHELL`?

**Comment by andersy005** [comment]
Unless `/bin/sh` links to `bash` on your system, you may want to use `bash` and see if the problem goes away.

**Comment by tinaok** [comment]
Thanks for your quick reply @andersy005 
yes, you are right is csh
!echo $SHELL
/bin/csh
I gave full path of ratermount, and it works.  (not so pretty though..)
I'll update my repo
